# Generated by Django 4.0.3 on 2022-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='profile_image',
            field=models.ImageField(default=' ', upload_to='media/'),
            preserve_default=False,
        ),
    ]
